#!/bin/sh

set -e

case "$1" in
	purge)
		rm -f /etc/shadowsocks-libev/config.json
		test -f /etc/shadowsocks-libev/* \
			|| rm -r /etc/shadowsocks-libev/
		;;
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		exit 0
		;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 0
		;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d shadowsocks-libev remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask shadowsocks-libev.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge shadowsocks-libev.service >/dev/null
		deb-systemd-helper unmask shadowsocks-libev.service >/dev/null
	fi
fi
# End automatically added section


exit 0
