#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/shadowsocks-libev" ] && [ "$1" = remove ]; then
	invoke-rc.d shadowsocks-libev stop || exit $?
fi
# End automatically added section
